### ISSUE TITLE
pacbio.vcf

### ISSUE THREAD

**Issue by liuhankui** [1dayac/novel_insertions_supplementary#1]
Dear Meleshko,

I found a pacbio.vcf in the folder: results/NA19240/ 
(https://github.com/1dayac/novel_insertions_supplementary/blob/master/results/NA19240/pacbio.vcf)

Are the SVs in pacbio.vcf file detected by Pacbio long read sequencing？

**Comment by 1dayac** [comment]
Yes,
These are the calls from
http://www-rcf.usc.edu/∼mchaisso/hgsvg/CombinedVCFs/NA19240.sv_calls.vcf.gz
<http://www-rcf.usc.edu/~mchaisso/hgsvg/CombinedVCFs/NA19240.sv_calls.vcf.gz>
They were initially published in
https://www.nature.com/articles/s41467-018-08148-z and we used them for
benchmarking purposes

Thanks,
Dmitry

вт, 18 апр. 2023 г. в 22:02, Vincent ***@***.***>:

**Comment by liuhankui** [comment]
> 

Thank you, Dmitry. I got it. 
The pacbio.vcf can provide some validations for my structure variant study. 

Hankui
